### ISSUE TITLE
Broken api

### ISSUE THREAD

**Issue by Rishabhg71** [yashraj-n/zoro-to-api#1]
Hi, I was planning to use this api to create a FireTV and Android TV app to watch anime on my TV but it seems to be broken
i executed the same snippet provided in README.md but it didnt work

seems like their API implementation is changed 

<details closed>

``` 
reject(new AxiosError(
           ^
AxiosError: Request failed with status code 404
    at settle (C:\Users\RG\Desktop\projects\test\node_modules\axios\lib\core\settle.js:19:12)
    at IncomingMessage.handleStreamEnd (C:\Users\RG\Desktop\projects\test\node_modules\axios\lib\adapters\http.js:548:11)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Accept-Encoding': '*r',
      Referer: 'https://zoro.to/',
      'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
      'User-Agent': 'axios/1.3.3'
    },
    method: 'get',
    url: 'https://zoro.to/ajax/v2/episode/list/Horimiya',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'zoro.to',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'zoro.to',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 319,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /ajax/v2/episode/list/Horimiya HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Accept-Encoding: *r\r\n' +
      'Referer: https://zoro.to/\r\n' +
      'Content-Type: application/x-www-form-urlencoded; charset=UTF-8\r\n' +
      'User-Agent: axios/1.3.3\r\n' +
      'Host: zoro.to\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/ajax/v2/episode/list/Horimiya',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://zoro.to/ajax/v2/episode/list/Horimiya',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 36,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'zoro.to',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://zoro.to/ajax/v2/episode/list/Horimiya',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kEndCalled)]: true,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'accept-encoding': [Array],
      referer: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 404,
    statusText: 'Not Found',
    headers: AxiosHeaders {
      date: 'Mon, 20 Feb 2023 09:13:19 GMT',
      'content-type': 'text/html; charset=utf-8',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'x-dns-prefetch-control': 'on',
      'expect-ct': 'max-age=0',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-download-options': 'noopen',
      'x-content-type-options': 'nosniff',
      'x-permitted-cross-domain-policies': 'none',
      'x-xss-protection': '0',
      vary: 'Accept-Encoding',
      'cf-cache-status': 'DYNAMIC',
      'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=k9RMBYXjODUQu14DG9g6d0Ljuf5HZ2mVaXx1iGioRs3cvAee2QlLMSShaM71IP1K0q2g0Tm3cPScodAVoAFjm2fISupm3rHHwA18qwxLIrbSehz%2F7sBQ9w53"}],"group":"cf-nel","max_age":604800}',
      nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
      server: 'cloudflare',
      'cf-ray': '79c62027ae896967-FRA',
      'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [AxiosHeaders],
      method: 'get',
      url: 'https://zoro.to/ajax/v2/episode/list/Horimiya',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /ajax/v2/episode/list/Horimiya HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Accept-Encoding: *r\r\n' +
        'Referer: https://zoro.to/\r\n' +
        'Content-Type: application/x-www-form-urlencoded; charset=UTF-8\r\n' +
        'User-Agent: axios/1.3.3\r\n' +
        'Host: zoro.to\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/ajax/v2/episode/list/Horimiya',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'zoro.to',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    data: '<!DOCTYPE html>\n' +
      '<html lang="en">\n' +
      '<head>\n' +
      '    <title>404 Error</title>\n' +
      '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>\n' +
      '<meta name="robots" content="index,follow"/>\n' +
      '<meta http-equiv="content-language" content="en"/>\n' +
      '<meta name="description" content="Zoro is a Free anime streaming website which you can watch English Subbed and Dubbed Anime online with No Account and Daily update. WATCH NOW!"/>\n' +
      '<meta name="keywords" content="anime to watch, watch anime,anime online, free anime online, online anime, anime streaming, stream anime online, english anime, english dubbed anime"/>\n' +
      '<meta property="og:type" content="website"/>\n' +
      '<meta property="og:url" content="https://zoro.to/ajax/v2/episode/list/Horimiya"/>\n' +
      '<meta property="og:title" content="404 Error"/>\n' +
      '<meta property="og:image" content="https://zoro.to/images/capture.png"/>\n' +
      '<meta property="og:image:width" content="650">\n' +
      '<meta property="og:image:height" content="350">\n' +
      '<meta property="og:description" content="Zoro is a Free anime streaming website which you can watch English Subbed and Dubbed Anime online with No Account and Daily update. WATCH NOW!"/>\n' +
      '<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1"/>\n' +
      '<meta name="apple-mobile-web-app-status-bar" content="#202125">\n' +
      '<meta name="theme-color" content="#202125">\n' +
      '<link rel="shortcut icon" href="/images/favicon.png?v=0.1" type="image/x-icon"/>\n' +
      '<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">\n' +
      '<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">\n' +
      '<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">\n' +
      '<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">\n' +
      '<meta name="msapplication-TileColor" content="#da532c">\n' +
      '<link rel="icon" sizes="192x192" href="/images/touch-icon-192x192.png?v=0.1">\n' +
      '<link rel="manifest" href="/manifest.json?v=0.2">\n' +
      '<!-- Global site tag (gtag.js) - Google Analytics -->\n' +
      '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-195414913-1"></script>\n' +
      '<script>\n' +
      '    window.dataLayer = window.dataLayer || [];\n' +
      '    function gtag() {\n' +
      '        dataLayer.push(arguments);\n' +
      '    }\n' +
      "    gtag('js', new Date());\n" +
      "    gtag('config', 'UA-195414913-1');\n" +
      '</script>\n' +
      '<script type="application/ld+json">\n' +
      '    {\n' +
      '        "@context": "https://schema.org",\n' +
      '        "@type": "WebSite",\n' +
      '        "url": "https://zoro.to/",\n' +
      '        "potentialAction": {\n' +
      '            "@type": "SearchAction",\n' +
      '            "target": "https://zoro.to/search?keyword={keyword}",\n' +
      '            "query-input": "required name=keyword"\n' +
      '        }\n' +
      '    }\n' +
      '</script>\n' +
      '<!--Begin: Stylesheet-->\n' +
      '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">\n' +
      '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">\n' +
      '<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">\n' +
      '<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">\n' +
      '<link rel="stylesheet" href="/css/styles.min.css?v=7.9">\n' +
      '<!--End: Stylesheet-->\n' +
      '</head>\n' +
      '<body>\n' +
      '<div id="wrapper">\n' +
      '    <div id="main-wrapper" class="layout-page layout-page-404">\n' +
      '        <div class="container">\n' +
      '            <div class="container-404 text-center">\n' +
      '                <div class="c4-big-img"><img src="/images/404.png?v=0.2" alt="404 image"></div>\n' +
      '                <div class="c4-medium">404 Error</div>\n' +
      '                <div class="c4-small">Oops! We can&#39;t find this page.</div>\n' +
      '                <div class="c4-button">\n' +
      '                    <a href="/home" class="btn btn-radius btn-focus">\n' +
      '                        <i class="fa fa-chevron-circle-left mr-2"></i>Back to homepage\n' +
      '                    </a>\n' +
      '                </div>\n' +
      '            </div>\n' +
      '            <div class="clearfix"></div>\n' +
      '        </div>\n' +
      '    </div>\n' +
      '</div>\n' +
      '\n' +
      "    <script>var recaptchaSiteKey = '6LcJeB8eAAAAAK9SJTPy75A2v4iIEOa-iNIpDzJM',\n" +
      "            recaptchaV2SiteKey = '6Lceeh8eAAAAAHpVJLDxIdPETkOv7HmZ8Rt3LMco';</script>\n" +
      '    <script src="https://www.google.com/recaptcha/api.js?render=6LcJeB8eAAAAAK9SJTPy75A2v4iIEOa-iNIpDzJM&hl=en"></script>\n' +
      '\n' +
      '<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-6086e5df0640b767" defer\n' +
      '        async></script>\n' +
      '<script src="https://cdn.socket.io/4.5.4/socket.io.min.js"\n' +
      '        integrity="sha384-/KNQL8Nu5gCHLqwqfQjA689Hhoqgi2S84SNUxC3roTe4EhJ9AfLkp8QiQcU8AMzI"\n' +
      '        crossorigin="anonymous"></script>\n' +
      '<script type="text/javascript" src="/js/app.min.js?v=9.3"></script>\n' +
      '<script>\n' +
      "    if ('serviceWorker' in navigator) {\n" +
      "        window.addEventListener('load', function () {\n" +
      "            navigator.serviceWorker.register('/sw.js?v=0.4');\n" +
      '        });\n' +
      '    }\n' +
      "    $('.anime-request-link').click(function (e) {\n" +
      '        e.preventDefault();\n' +
      '        if (isLoggedIn) {\n' +
      "            window.location.href = $(this).attr('href');\n" +
      '        } else {\n' +
      "            $('#modallogin').modal('show');\n" +
      '        }\n' +
      '    });\n' +
      '\n' +
      '    function timeFormatBySeconds(seconds) {\n' +
      '        const d = Math.floor(seconds / (3600 * 24)), h = Math.floor(seconds / 3600 % 24),\n' +
      '            m = Math.floor(seconds % 3600 / 60),\n' +
      '            s = Math.floor(seconds % 3600 % 60);\n' +
      '\n' +
      `        var dDisplay = d > 0 ? (d < 10 ? '0' + d : d) + " : " : "",\n` +
      `            hDisplay = h > 0 ? (h < 10 ? '0' + h : h) + " : " : "",\n` +
      `            mDisplay = m > 0 ? (m < 10 ? '0' + m : m) + " : " : "00 : ",\n` +
      `            sDisplay = s > 0 ? (s < 10 ? '0' + s : s) : "00";\n` +
      '\n' +
      '        return dDisplay + hDisplay + mDisplay + sDisplay;\n' +
      '    }\n' +
      '</script>\n' +
      `<script data-cfasync="false" type="text/javascript">(function($,document){for($._Eu=$.BD;$._Eu<$.Fo;$._Eu+=$.y){switch($._Eu){case $.Fl:!function(r){for($._E=$.BD;$._E<$.Cf;$._E+=$.y){switch($._E){case $.CB:u.m=r,u.c=e,u.d=function(n,t,r){u.o(n,t)||Object[$.e](n,t,$.$($.BF,!$.y,$.Ck,!$.BD,$.Ch,r));},u.n=function(n){for($._C=$.BD;$._C<$.CB;$._C+=$.y){switch($._C){case $.y:return u.d(t,$.Ca,t),t;break;case $.BD:var t=n&&n[$.Cc]?function(){return n[$.Ci];}:function(){return n;};break;}}},u.o=function(n,t){return Object[$.CF][$.CJ][$.Bz](n,t);},u.p=$.Bu,u(u.s=$.Bx);break;case $.y:function u(n){for($._B=$.BD;$._B<$.Cf;$._B+=$.y){switch($._B){case $.CB:return r[n][$.Bz](t[$.Bw],t,t[$.Bw],u),t.l=!$.BD,t[$.Bw];break;case $.y:var t=e[n]=$.$($.CC,n,$.CE,!$.y,$.Bw,$.$());break;case $.BD:if(e[n])return e[n][$.Bw];break;}}}break;case $.BD:var e=$.$();break;}}}([function(n,t,r){for($._g=$.BD;$._g<$.Cf;$._g+=$.y){switch($._g){case $.CB:t.e=5419284,t.a=5419283,t.v=3,t.w=1,t.h=30,t.y=1,t._=true,t.g=g[$.Jw](b('eyJhZGJsb2NrIjp7fSwiZXhjbHVkZXMiOiIifQ==')),t.O=1,t.k='Ly90aGF1ZHJheS5jb20vNS81NDE5Mjg0',t.A=2,t.S=$.Iq*1671909906,t.P='V2@%YSU2B]G~',t.M='pw2',t.T='d8g3vf2xf0u',t.B='43ie9ihiOex604ew4Kbnorry4gVp4u2qsyl',t.N='2pnWxbyTednS9zy',t.I='e9rmhyzm92d',t.C='_uezbvr',t.R='_aevrntm';break;case $.y:Object[$.e](t,$.Cc,$.$($.Ik,!$.BD));break;case $.BD:$.Cr;break;}}},function(n,t,e){for($._DI=$.BD;$._DI<$.DC;$._DI+=$.y){switch($._DI){case $.Cf:function w(){for($._DH=$.BD;$._DH<$.CB;$._DH+=$.y){switch($._DH){case $.y:t[$.Ih](s.J,$.Gr+($.BD,f.Z)()),t[$.Ii](s.$,c.Q[d.O]),t[$.Il]=function(){if($.ad===t[$.bJ]){for($._DA=$.BD;$._DA<$.CB;$._DA+=$.y){switch($._DA){case $.y:n[$.l](function(n){for($._Bb=$.BD;$._Bb<$.CB;$._Bb+=$.y){switch($._Bb){case $.y:u[r]=e;break;case $.BD:var t=n[$.Gv]($.dy),r=t[$.cj]()[$.eF](),e=t[$.Bt]($.dy);break;}}}),u[s.W]?(l=!$.BD,($.BD,a.nn)(u[s.W])):u[s.tn]&&($.BD,a.nn)(u[s.tn]);break;case $.BD:var n=t[$.cr]()[$.dd]()[$.Gv](new RegExp($.dz,$.Bu)),u=$.$();break;}}}},t[$.Ij]();break;case $.BD:var t=new window[$.Jj]();break;}}}break;case $.y:Object[$.e](t,$.Cc,$.$($.Ik,!$.BD)),t[$.Di]=function(){return $.Jt+d.e+$.bh;},t.z=function(){return $.Jz+d.e;},t.D=function(){return($.BD,a.H)();},t.F=function(){return[($.BD,u.L)(o.G[$.Ds],o[$.Go][$.Ds]),($.BD,u.L)(o[$.Er][$.Ds],o[$.Go][$.Ds])][$.Bt]($.bp);},t.V=function(){for($._Bd=$.BD;$._Bd<$.CB;$._Bd+=$.y){switch($._Bd){case $.y:n.id=i.U,window[$.JI](n,$.Jv);break;case $.BD:var n=$.$(),t=r(function(){($.BD,f.X)()&&(v(t),w());},$.Jk);break;}}},t.Y=w,t.K=function(){return new Promise(function(t,e){var u=$.BD,i=r(function(){for($._CH=$.BD;$._CH<$.CB;$._CH+=$.y){switch($._CH){case $.y:n?(v(i),l&&(($.BD,f[$.Dq])(),t(n)),t()):$.Fo<=u&&(v(i),e()),u+=$.y;break;case $.BD:var n=($.BD,a.H)();break;}}},$.Jk);});};break;case $.CB:var u=e($.CB),i=e($.Cf),o=e($.Fk),c=e($.Fl),f=e($.Fm),a=e($.Fn),d=e($.BD),s=e($.Fo),l=!$.y;break;case $.BD:$.Cr;break;}}},function(n,t,r){for($._CJ=$.BD;$._CJ<$.Ft;$._CJ+=$.y){switch($._CJ){case $.Cf:function a(n){for($._Bk=$.BD;$._Bk<$.CB;$._Bk+=$.y){switch($._Bk){case $.y:return e<=t&&t<=u?t-e:o<=t&&t<=c?t-o+i:$.BD;break;case $.BD:var t=n[$.Bv]()[$.bC]($.BD);break;}}}break;case $.y:Object[$.e](t,$.Cc,$.$($.Ik,!$.BD)),t[$.Dj]=a,t[$.o]=d,t.rn=function(n,u){return n[$.Gv]($.Bu)[$.aa](function(n,t){for($._BF=$.BD;$._BF<$.CB;$._BF+=$.y){switch($._BF){case $.y:return d(e);break;case $.BD:var r=(u+$.y)*(t+$.y),e=(a(n)+r)%f;break;}}})[$.Bt]($.Bu);},t.en=function(n,u){return n[$.Gv]($.Bu)[$.aa](function(n,t){for($._Bf=$.BD;$._Bf<$.CB;$._Bf+=$.y){switch($._Bf){case $.y:return d(e);break;case $.BD:var r=u[t%(u[$.Gp]-$.y)],e=(a(n)+a(r))%f;break;}}})[$.Bt]($.Bu);},t.L=function(n,c){return n[$.Gv]($.Bu)[$.aa](function(n,t){for($._Ba=$.BD;$._Ba<$.CB;$._Ba+=$.y){switch($._Ba){case $.y:return d(o);break;case $.BD:var r=c[t%(c[$.Gp]-$.y)],e=a(r),u=a(n),i=u-e,o=i<$.BD?i+f:i;break;}}})[$.Bt]($.Bu);};break;case $.DC:function d(n){return n<=$.Fl?k[$.o](n+e):n<=$.ck?k[$.o](n+o-i):k[$.o](e);}break;case $.CB:var e=$.Ct,u=$.Cu,i=u-e+$.y,o=$.Cv,c=$.Cw,f=c-o+$.y+i;break;case $.BD:$.Cr;break;}}},function(t,r,u){for($._Cz=$.BD;$._Cz<$.Ft;$._Cz+=$.y){switch($._Cz){case $.Cf:r.cn=f[$.Bn]()[$.Bv]($.By)[$.CA]($.CB),r.in=f[$.Bn]()[$.Bv]($.By)[$.CA]($.CB),r.U=f[$.Bn]()[$.Bv]($.By)[$.CA]($.CB),r.un=f[$.Bn]()[$.Bv]($.By)[$.CA]($.CB);break;case $.y:Object[$.e](r,$.Cc,$.$($.Ik,!$.BD)),r.un=r.U=r.in=r.cn=r.fn=r.an=void $.BD;break;case $.DC:c&&(c[$.B](a,function t(r){c[$.C](a,t),[($.BD,i.dn)`... 55015 more characters
  }
}

```
</details>

**Comment by yashraj-n** [comment]
Seems like they changed the API, will look into it when I get time.

**Comment by yashraj-n** [comment]
There was a typo in README, `getEpList` expects id of episode, README was having `eng_title`. Zoro.to didnt change their API.

**Comment by Rishabhg71** [comment]
@yashraj-n i would like a little help from your side to complete my project
I want to know how you managed to get the API data from zoro.to because whenever I open developer tools on zoro.to it just hits a breakpoint and redirects me to the homepage. I need to get some data from developers any chance you could help me with this

**Comment by yashraj-n** [comment]
Use traffic capturing tools to capture network requests. In my case I used Burpsuite. You can also scrape the webpage and get specific data using cheerio.

**Comment by Rishabhg71** [comment]
@yashraj-n hm i had this idea and it did work. Sorry for being a little vague but i need to check HTML elements and make DOM operations

**Comment by yashraj-n** [comment]
Try using cheerio, I've used cheerio in my repo to parse html data into usable format.

**Comment by Rishabhg71** [comment]
@yashraj-n I tried reverse engineering the script and going through the call stack and found the exact library that is used after a little digging I found the repo/npm package 
reading the docs they clearly mentioned that this library doesn't work on firefox if the console is undocked.
I thought it might help you too next time 

library that was used : https://github.com/AEPKILL/devtools-detector#caveats
thanks for your help too 🤝



EDIT : Nvm it worked on demo page of the package but not on actual site

**Comment by yashraj-n** [comment]
Using firefox just redirects me to zoro.to/home

**Comment by Rishabhg71** [comment]
@yashraj-n again one more update going through the call stack again i found a trick that worked on chrome 

https://zoro.to/watch/tokyo-revengers-christmas-showdown-18244?ep=98522&_debug=ok
if you add a _debug=ok in the URL param in the end it doesn't redirect but still hits the breakpoint (seems like a loop is running ) but you can disable breakpoints and work as usual
let me know if this works for you 

This was the exact code that was redirecting us

```javascript
var t = new URL(window.location.href)
t = new URLSearchParams(t.search);
e && "ok" !== t.get("_debug") && (window.location.href = "/home")
```

**Comment by yashraj-n** [comment]
Great research, looks like they use `_debug` option to test some things on site
